<a href="https://colab.research.google.com/github/mostofa89/NumPy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
nums = np.array([1, 2, 3])

print(nums)

[1 2 3]


In [3]:
arr = np.array([[3.5, 4.5, 6], [7, 8, 9.10]])
nums = np.array([1, 2, 3], dtype='int16')
print(arr)
print(arr.ndim)  # print Dimentions
print(arr.shape) # Print Shape
print(arr.dtype) # print the data type
print(nums.dtype)
print(arr.size) # to the length
print(nums.itemsize) # return the size in bytes
print(arr.itemsize)

[[3.5 4.5 6. ]
 [7.  8.  9.1]]
2
(2, 3)
float64
int16
6
2
8


In [ ]:
arr1=np.arange(1,10)
print(arr1)
arr2=np.arange(1,10).reshape(3,3)
print(arr2)

eight=np.where(arr1%2==0)
print(eight)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(array([1, 3, 5, 7]),)


In [ ]:
ran=np.random.randint(1,11,4).reshape(2,2)
print(ran)

[[10  5]
 [ 3 10]]
