<a href="https://colab.research.google.com/github/mostofa89/NumPy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
nums = np.array([1, 2, 3])

print(nums)

[1 2 3]


In [3]:
arr = np.array([[3.5, 4.5, 6], [7, 8, 9.10]])
nums = np.array([1, 2, 3], dtype='int16')
print(arr)
print(arr.ndim)  # print Dimentions
print(arr.shape) # Print Shape
print(arr.dtype) # print the data type
print(nums.dtype)
print(arr.size) # to the length
print(nums.itemsize) # return the size in bytes
print(arr.itemsize)

[[3.5 4.5 6. ]
 [7.  8.  9.1]]
2
(2, 3)
float64
int16
6
2
8


In [6]:
#get Total size
print(arr.nbytes)

48


In [3]:
nums = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(nums)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# get specific element [r, c]
print(nums[2, 2])
print(nums[2][2])

9
9


In [17]:
# get Specific row

print(nums[1])
print(nums[0, :])
print(nums[:1]) # give nd Row

[4 5 6]
[1 2 3]
[[1 2 3]]


In [9]:
# get specific column
print(nums[ :, 2])

[3 6 9]


#Slicing

In [34]:
nums = np.arange(1, 10).reshape(3, 3)
arr = np.arange(1, 10)

In [36]:
print(nums[0:2])
print(arr[0:2])

[[1 2 3]
 [4 5 6]]
[1 2]


In [20]:
#need [5 6]
print(nums[1][1:3])

[5 6]


In [37]:
print(nums[1:3:1])
print(arr[1:3:2])

[[4 5 6]
 [7 8 9]]
[2]


In [52]:
# starting : ending : step
print(arr[::2])
print(nums[::1])

[1 3 5 7 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
# row, col-starting, ending
print(nums[2, 0:3])
print(nums[1, 1:3])

[7 8 9]
[5 6]


In [64]:
#row-staring:row-ending, col-number
print(nums[1:3, 1])
print(nums[0:3, 2])

[5 8]
[3 6 9]


In [68]:
#row-staring:row-ending, col-starting, col-ending
print(nums[0:2, 1:4])

[[2 3]
 [5 6]]


In [65]:
ran=np.random.randint(1,11,9).reshape(3,3)
print(ran)

[[9 9 5]
 [4 4 3]
 [7 9 3]]
