<a href="https://colab.research.google.com/github/mostofa89/NumPy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
nums = np.array([1, 2, 3])

print(nums)

[1 2 3]


In [3]:
arr = np.array([[3.5, 4.5, 6], [7, 8, 9.10]])
nums = np.array([1, 2, 3], dtype='int16')
print(arr)
print(arr.ndim)  # print Dimentions
print(arr.shape) # Print Shape
print(arr.dtype) # print the data type
print(nums.dtype)
print(arr.size) # to the length
print(nums.itemsize) # return the size in bytes
print(arr.itemsize)

[[3.5 4.5 6. ]
 [7.  8.  9.1]]
2
(2, 3)
float64
int16
6
2
8


In [4]:
#get Total size
print(arr.nbytes)

48


In [5]:
nums = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(nums)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# get specific element [r, c]
print(nums[2, 2])
print(nums[2][2])

9
9


In [7]:
# get Specific row

print(nums[1])
print(nums[0, :])
print(nums[:1]) # give nd Row

[4 5 6]
[1 2 3]
[[1 2 3]]


In [8]:
# get specific column
print(nums[ :, 2])

[3 6 9]


#Slicing

In [9]:
nums = np.arange(1, 10).reshape(3, 3)
arr = np.arange(1, 10)

In [10]:
print(nums[0:2])
print(arr[0:2])

[[1 2 3]
 [4 5 6]]
[1 2]


In [11]:
#need [5 6]
print(nums[1][1:3])

[5 6]


In [12]:
print(nums[1:3:1])
print(arr[1:3:2])

[[4 5 6]
 [7 8 9]]
[2]


In [13]:
# starting : ending : step
print(arr[::2])
print(nums[::1])

[1 3 5 7 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# row, col-starting, ending
print(nums[2, 0:3])
print(nums[1, 1:3])

[7 8 9]
[5 6]


In [15]:
#row-staring:row-ending, col-number
print(nums[1:3, 1])
print(nums[0:3, 2])

[5 8]
[3 6 9]


In [16]:
#row-staring:row-ending, col-starting, col-ending
print(nums[0:2, 1:4])

[[2 3]
 [5 6]]


#Copy as View

In [17]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


#Shape

In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 7], ndmin=4)

print(arr)
print('shape of array :', arr.shape)

[[[[1 2 3 4 5 7]]]]
shape of array : (1, 1, 1, 6)


#Reshape

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], ndmin=4)

print(arr)
nums = arr.reshape(3,3)
print(nums)

[[[[1 2 3 4 5 6 7 8 9]]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr.base)

[1 2 3 4 5 6 7 8]


In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(1, 6)
nums = arr.reshape(-1)

print(newarr)
print(nums)

[[1 2 3 4 5 6]]
[1 2 3 4 5 6]


#Iterating Numpy Array

In [25]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x, end = " ")

1 2 3 

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2d Array

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2d Array

for items in arr:
  for i in items:
    print(i, end = " ")

1 2 3 4 5 6 

In [28]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 3d Array

for x in arr:
  for y in x:
    for z in y:
      print(z, end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [29]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3D Array

for x in np.nditer(arr):
  print(x, end = " ")

1 2 3 4 5 6 7 8 

In [30]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


# Join or Concatinate

In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

arr = np.hstack((arr1, arr2, arr3)) # join into 1D array

print(arr)

[1 2 3 4 5 6 7 8 9]


In [34]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

arr = np.vstack((arr1, arr2, arr3)) # join into 2D array

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
arr4 = np.array([10, 11, 12])

arr = np.dstack((arr1, arr2, arr3)) # Join into 3D array

print(arr)

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


#Split

In [41]:
arr = np.array([1, 2, 3, 4, 5, 6])

nums1, nums2 = np.array_split(arr, 2) # split into array

print(nums1)
print(nums2)

[1 2 3]
[4 5 6]


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Search in Numpy array

In [44]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4) # return the index of the element

print(x)

(array([3, 5, 6]),)


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

x = np.where(arr%2 == 0) # return the index

print(x)

(array([ 1,  3,  5,  7,  9, 11, 13]),)


In [53]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15])

x = np.where(arr%2 == 1) # return the index

print(x)

(array([ 0,  2,  4,  6,  8, 10, 12, 13]),)


#Sorting

In [59]:
arr = np.array([6, 8, 10, 7, 9])

sorted_arr = np.sort(arr)
print(x)

[ 6  7  8  9 10]


In [61]:
arr = np.array(['banana', 'Lichi', 'Mango' 'cherry', 'apple'])

print(np.sort(arr)) # First it will sorted uppercase ten lowercase

['Lichi' 'Mangocherry' 'apple' 'banana']


In [63]:
arr = np.array([True, False, True, False])

print(np.sort(arr))

[False False  True  True]


In [64]:
arr = np.array([[3, 2, 4, 6], [5, 0, 1, 7]])

print(np.sort(arr))

[[2 3 4 6]
 [0 1 5 7]]


#Filter

In [66]:
arr = np.array([41, 42, 43, 44, 45])

x = [True, False, True, False, True]

newarr = arr[x]

print(newarr)

[41 43 45]


In [69]:
#Creating a fillter array which elements is grater than 15
arr = np.array([41, 10, 15, 11, 42, 43, 44, 45, 59, 70, 90])

filter_arr = []

for num in arr:
  if num > 15:
    filter_arr.append(True)

  else:
    filter_arr.append(False)

new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[True, False, False, False, True, True, True, True, True, True, True]
[41 42 43 44 45 59 70 90]


In [72]:
#Creating a fillter array which elements is divisible by 3
arr = np.array([41, 10, 15, 11, 42, 43, 44, 45, 59, 70, 90])

filter_arr = []

for num in arr:
  if num %3 == 0:
    filter_arr.append(True)

  else:
    filter_arr.append(False)

new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[False, False, True, False, True, False, False, True, False, False, True]
[15 42 45 90]


In [74]:
filter_arr = arr > 15

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[ True False False False  True  True  True  True  True  True  True]
[41 42 43 44 45 59 70 90]


In [76]:
filter_arr = (arr % 3) == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True False  True False False  True False False  True]
[15 42 45 90]
